"""empty message

Revision ID: 3f2546f228d8
Revises: 5d1fb7a39527
Create Date: 2018-01-11 14:46:27.252525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2546f228d8'
down_revision = '5d1fb7a39527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interface_detail', sa.Column('header', sa.String(length=255), nullable=True))
    op.add_column('interface_detail', sa.Column('is_sign', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interface_detail', 'is_sign')
    op.drop_column('interface_detail', 'header')
    # ### end Alembic commands ###
