"""empty message

Revision ID: 3f70b23b4ea5
Revises: 3f2546f228d8
Create Date: 2018-01-11 14:48:11.750488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f70b23b4ea5'
down_revision = '3f2546f228d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interface_detail', sa.Column('cookie', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interface_detail', 'cookie')
    # ### end Alembic commands ###
