"""empty message

Revision ID: 5d1fb7a39527
Revises: 
Create Date: 2018-01-09 19:47:22.201854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1fb7a39527'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interface_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_name', sa.String(length=255), nullable=True),
    sa.Column('interface_type', sa.String(length=50), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('request_sample', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_manage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('project_description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sql_statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sql_description', sa.String(length=255), nullable=True),
    sa.Column('sql_statement', sa.String(length=255), nullable=True),
    sa.Column('expect_result', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testcase_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_data', sa.String(length=255), nullable=True),
    sa.Column('expect_result', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testcase_info',
    sa.Column('tc_id', sa.Integer(), nullable=False),
    sa.Column('tc_name', sa.String(length=200), nullable=True),
    sa.Column('tc_description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('tc_id')
    )
    op.create_table('testsuite_info',
    sa.Column('ts_id', sa.Integer(), nullable=False),
    sa.Column('ts_name', sa.String(length=200), nullable=True),
    sa.Column('ts_description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('ts_id')
    )
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('model_description', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project_manage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tc_db_relative',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tc_id', sa.Integer(), nullable=True),
    sa.Column('sql_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sql_id'], ['sql_statement.id'], ),
    sa.ForeignKeyConstraint(['tc_id'], ['testcase_info.tc_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testsuite_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts_id', sa.Integer(), nullable=True),
    sa.Column('ts_name', sa.String(length=200), nullable=True),
    sa.Column('tc_id', sa.Integer(), nullable=True),
    sa.Column('tc_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['tc_id'], ['testcase_info.tc_id'], ),
    sa.ForeignKeyConstraint(['tc_name'], ['testcase_info.tc_name'], ),
    sa.ForeignKeyConstraint(['ts_id'], ['testsuite_info.ts_id'], ),
    sa.ForeignKeyConstraint(['ts_name'], ['testsuite_info.ts_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=63), nullable=True),
    sa.Column('password', sa.String(length=252), nullable=True),
    sa.Column('user_email', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('testsuite_detail')
    op.drop_table('tc_db_relative')
    op.drop_table('project_model')
    op.drop_table('works')
    op.drop_table('testsuite_info')
    op.drop_table('testcase_info')
    op.drop_table('testcase_detail')
    op.drop_table('sql_statement')
    op.drop_table('roles')
    op.drop_table('project_manage')
    op.drop_table('interface_detail')
    # ### end Alembic commands ###
